import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  // 2 Admin
  await prisma.admin.upsert({
    where: { username: "admin1" },
    update: {},
    create: {
      username: "admin1",
      password: await bcrypt.hash("admin123", 10),
      name: "Admin One",
    },
  });

  await prisma.admin.upsert({
    where: { username: "admin2" },
    update: {},
    create: {
      username: "admin2",
      password: await bcrypt.hash("admin456", 10),
      name: "Admin Two",
    },
  });

  // 5 Major
  const cs = await prisma.major.upsert({
    where: { name: "Computer Science" },
    update: {},
    create: { name: "Computer Science", description: "Computer Science Major" },
  });

  const it = await prisma.major.upsert({
    where: { name: "Information Technology" },
    update: {},
    create: {
      name: "Information Technology",
      description: "Information Technology Major",
    },
  });

  const eng = await prisma.major.upsert({
    where: { name: "Engineering" },
    update: {},
    create: { name: "Engineering", description: "Engineering Major" },
  });

  const biz = await prisma.major.upsert({
    where: { name: "Business Administration" },
    update: {},
    create: {
      name: "Business Administration",
      description: "Business Administration Major",
    },
  });

  const is = await prisma.major.upsert({
    where: { name: "Information Systems" },
    update: {},
    create: {
      name: "Information Systems",
      description: "Information Systems Major",
    },
  });

  // Students — CS:12, IT:9, Eng:7, Biz:5, IS:2 = total 35
  const students = [
    // ── Computer Science (12) ──────────────────────────────
    {
      studentId: "STU001",
      name: "Aung Aung",
      age: 20,
      township: "Yangon",
      gender: "Male",
      email: "aung@email.com",
      phone: "09111111111",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU002",
      name: "Ma Htwe",
      age: 21,
      township: "Mandalay",
      gender: "Female",
      email: "mahtwe@email.com",
      phone: "09222222222",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU003",
      name: "Kyaw Min",
      age: 22,
      township: "Bago",
      gender: "Male",
      email: "kyawmin@email.com",
      phone: "09333333333",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU004",
      name: "Pyae Sone",
      age: 21,
      township: "Yangon",
      gender: "Male",
      email: "pyaesone@email.com",
      phone: "09200000001",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU005",
      name: "Hnin Wai",
      age: 20,
      township: "Mandalay",
      gender: "Female",
      email: "hninwai@email.com",
      phone: "09200000002",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU006",
      name: "Zin Ko",
      age: 22,
      township: "Sagaing",
      gender: "Male",
      email: "zinko@email.com",
      phone: "09200000003",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU007",
      name: "Khin Yadanar",
      age: 21,
      township: "Bago",
      gender: "Female",
      email: "khinyadanar@email.com",
      phone: "09200000004",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU008",
      name: "Myo Thant",
      age: 23,
      township: "Thanlyin",
      gender: "Male",
      email: "myothant@email.com",
      phone: "09300000001",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU009",
      name: "Thazin Oo",
      age: 20,
      township: "Insein",
      gender: "Female",
      email: "thazinoo@email.com",
      phone: "09300000002",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU010",
      name: "Ye Htet",
      age: 22,
      township: "Tharkayta",
      gender: "Male",
      email: "yehtet@email.com",
      phone: "09300000003",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU011",
      name: "Nang Kham",
      age: 21,
      township: "Lashio",
      gender: "Female",
      email: "nangkham@email.com",
      phone: "09300000004",
      majorId: cs.id,
      academicYear: 2026,
    },
    {
      studentId: "STU012",
      name: "Sithu Kyaw",
      age: 20,
      township: "Taunggyi",
      gender: "Male",
      email: "sithukyaw@email.com",
      phone: "09300000005",
      majorId: cs.id,
      academicYear: 2026,
    },

    // ── Information Technology (9) ─────────────────────────
    {
      studentId: "STU013",
      name: "Su Su",
      age: 20,
      township: "Pathein",
      gender: "Female",
      email: "susu@email.com",
      phone: "09444444444",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU014",
      name: "Kyaw Zin",
      age: 23,
      township: "Mawlamyine",
      gender: "Male",
      email: "kyawzin@email.com",
      phone: "09555555555",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU015",
      name: "Thida Win",
      age: 21,
      township: "Naypyidaw",
      gender: "Female",
      email: "thidawin@email.com",
      phone: "09666666666",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU016",
      name: "Naing Lin",
      age: 23,
      township: "Pathein",
      gender: "Male",
      email: "nainglin@email.com",
      phone: "09200000005",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU017",
      name: "Phyu Sin",
      age: 20,
      township: "Mawlamyine",
      gender: "Female",
      email: "phyusin@email.com",
      phone: "09200000006",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU018",
      name: "Aung Zaw",
      age: 22,
      township: "Naypyidaw",
      gender: "Male",
      email: "aungzaw@email.com",
      phone: "09200000007",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU019",
      name: "Su Myat",
      age: 21,
      township: "Pyay",
      gender: "Female",
      email: "sumyat@email.com",
      phone: "09200000008",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU020",
      name: "Hein Htet",
      age: 22,
      township: "Myeik",
      gender: "Male",
      email: "heinhtet@email.com",
      phone: "09300000006",
      majorId: it.id,
      academicYear: 2026,
    },
    {
      studentId: "STU021",
      name: "Wut Yee",
      age: 20,
      township: "Kyaukse",
      gender: "Female",
      email: "wutyee@email.com",
      phone: "09300000007",
      majorId: it.id,
      academicYear: 2026,
    },

    // ── Engineering (7) ───────────────────────────────────
    {
      studentId: "STU022",
      name: "Zaw Lin",
      age: 22,
      township: "Taunggyi",
      gender: "Male",
      email: "zawlin@email.com",
      phone: "09777777777",
      majorId: eng.id,
      academicYear: 2026,
    },
    {
      studentId: "STU023",
      name: "Aye Myat",
      age: 20,
      township: "Pyay",
      gender: "Female",
      email: "ayemyat@email.com",
      phone: "09888888888",
      majorId: eng.id,
      academicYear: 2026,
    },
    {
      studentId: "STU024",
      name: "Min Ko",
      age: 21,
      township: "Magway",
      gender: "Male",
      email: "minko@email.com",
      phone: "09999999999",
      majorId: eng.id,
      academicYear: 2026,
    },
    {
      studentId: "STU025",
      name: "Thiha Zaw",
      age: 22,
      township: "Taunggyi",
      gender: "Male",
      email: "thihazaw@email.com",
      phone: "09200000009",
      majorId: eng.id,
      academicYear: 2026,
    },
    {
      studentId: "STU026",
      name: "Myat Noe",
      age: 20,
      township: "Magway",
      gender: "Female",
      email: "myatnoe@email.com",
      phone: "09200000010",
      majorId: eng.id,
      academicYear: 2026,
    },
    {
      studentId: "STU027",
      name: "Ko Ko Aung",
      age: 23,
      township: "Meiktila",
      gender: "Male",
      email: "kokoaung@email.com",
      phone: "09200000011",
      majorId: eng.id,
      academicYear: 2026,
    },
    {
      studentId: "STU028",
      name: "Wai Phyo",
      age: 21,
      township: "Monywa",
      gender: "Male",
      email: "waiphyo@email.com",
      phone: "09200000012",
      majorId: eng.id,
      academicYear: 2026,
    },

    // ── Business Administration (5) ───────────────────────
    {
      studentId: "STU029",
      name: "Nwe Ni",
      age: 22,
      township: "Monywa",
      gender: "Female",
      email: "nweni@email.com",
      phone: "09100000000",
      majorId: biz.id,
      academicYear: 2026,
    },
    {
      studentId: "STU030",
      name: "Htet Aung",
      age: 20,
      township: "Meiktila",
      gender: "Male",
      email: "htetaung@email.com",
      phone: "09100000001",
      majorId: biz.id,
      academicYear: 2026,
    },
    {
      studentId: "STU031",
      name: "Ei Phyu",
      age: 21,
      township: "Shwebo",
      gender: "Female",
      email: "eiphyu@email.com",
      phone: "09100000002",
      majorId: biz.id,
      academicYear: 2026,
    },
    {
      studentId: "STU032",
      name: "Soe Htet",
      age: 20,
      township: "Shwebo",
      gender: "Male",
      email: "soehtet@email.com",
      phone: "09200000013",
      majorId: biz.id,
      academicYear: 2026,
    },
    {
      studentId: "STU033",
      name: "Aye Aye",
      age: 22,
      township: "Lashio",
      gender: "Female",
      email: "ayeaye@email.com",
      phone: "09200000014",
      majorId: biz.id,
      academicYear: 2026,
    },

    // ── Information Systems (2) ───────────────────────────
    {
      studentId: "STU034",
      name: "Kaung Htet",
      age: 23,
      township: "Lashio",
      gender: "Male",
      email: "kaunghtet@email.com",
      phone: "09100000003",
      majorId: is.id,
      academicYear: 2026,
    },
    {
      studentId: "STU035",
      name: "Thin Zar",
      age: 20,
      township: "Myitkyina",
      gender: "Female",
      email: "thinzar@email.com",
      phone: "09100000004",
      majorId: is.id,
      academicYear: 2026,
    },
  ];

  for (const student of students) {
    await prisma.student.upsert({
      where: { studentId: student.studentId },
      update: {},
      create: student,
    });
  }

  console.log("✅ Seeded: 2 Admins, 5 Majors, 35 Students");
  console.log("   CS: 12 | IT: 9 | Eng: 7 | Biz: 5 | IS: 2");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
